In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

path = r"/Users/mac/Desktop/archive (1)/test.csv"
assert os.path.isfile(path)
with open(path, "r") as f:
    pass

In [3]:
data = pd.read_csv('/Users/mac/Desktop/archive (1)/train.csv')
test = pd.read_csv('/Users/mac/Desktop/archive (1)/test.csv')

In [4]:
data

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0         Owner                   0     0        2       BHK  1300.236407   
1        Dealer                   0     0        2       BHK  1275.000000   
2         Owner                   0     0        2       BHK   933.159722   
3         Owner                   0     1        2       BHK   929.921143   
4        Dealer                   1     0        2       BHK   999.009247   
...         ...                 ...   ...      ...       ...          ...   
29446     Owner                   0     0        3       BHK  2500.000000   
29447     Owner                   0     0        2       BHK   769.230769   
29448    Dealer                   0     0        2       BHK  1022.641509   
29449     Owner                   0     0        2       BHK   927.079009   
29450    Dealer                   0     1        2       BHK   896.774194   

       READY_TO_MOVE  RESALE                            ADDRESS  LONGITUDE  \
0                  1       1              Ksfc Layout,Bangalore  12.969910   
1                  1       1          Vishweshwara Nagar,Mysore  12.274538   
2                  1       1                   Jigani,Bangalore  12.778033   
3                  1       1        Sector-1 Vaishali,Ghaziabad  28.642300   
4                  0       1                   New Town,Kolkata  22.592200   
...              ...     ...                                ...        ...   
29446              1       1               Shamshabad Road,Agra  27.140626   
29447              1       1  E3-108, Lake View Recidency,,Vapi  39.945409   
29448              1       1                  Ajmer Road,Jaipur  26.928785   
29449              1       1             Sholinganallur,Chennai  12.900150   
29450              1       1                   Jagatpura,Jaipur  26.832353   

        LATITUDE  TARGET(PRICE_IN_LACS)  
0      77.597960                   55.0  
1      76.644605                   51.0  
2      77.632191                   43.0  
3      77.344500                   62.5  
4      88.484911                   60.5  
...          ...                    ...  
29446  78.043277                   45.0  
29447 -86.150721                   16.0  
29448  75.828002                   27.1  
29449  80.227910                   67.0  
29450  75.841749                   27.8  

[29451 rows x 12 columns]

In [5]:
data.isnull().sum()

POSTED_BY                0
UNDER_CONSTRUCTION       0
RERA                     0
BHK_NO.                  0
BHK_OR_RK                0
SQUARE_FT                0
READY_TO_MOVE            0
RESALE                   0
ADDRESS                  0
LONGITUDE                0
LATITUDE                 0
TARGET(PRICE_IN_LACS)    0
dtype: int64

In [6]:
data['POSTED_BY'].value_counts()

Dealer     18291
Owner      10538
Builder      622
Name: POSTED_BY, dtype: int64

In [7]:
posted_by = pd.get_dummies(data['POSTED_BY'])
data = pd.concat([data, posted_by], axis = 1)
data.drop(columns = ['POSTED_BY'], inplace = True)

In [8]:
data['BHK_OR_RK'].value_counts()

BHK    29427
RK        24
Name: BHK_OR_RK, dtype: int64

In [9]:
for i in data['BHK_OR_RK']:
    if i == 'BHK':
        data['BHK_OR_RK'].replace('BHK', 1, inplace = True)
    elif i == 'RK':
        data['BHK_OR_RK'].replace('RK', 0, inplace = True)

In [10]:
data['BHK_OR_RK'].value_counts()

1    29427
0       24
Name: BHK_OR_RK, dtype: int64

In [11]:
data.drop(columns = ['ADDRESS'], inplace = True)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   UNDER_CONSTRUCTION     29451 non-null  int64  
 1   RERA                   29451 non-null  int64  
 2   BHK_NO.                29451 non-null  int64  
 3   BHK_OR_RK              29451 non-null  int64  
 4   SQUARE_FT              29451 non-null  float64
 5   READY_TO_MOVE          29451 non-null  int64  
 6   RESALE                 29451 non-null  int64  
 7   LONGITUDE              29451 non-null  float64
 8   LATITUDE               29451 non-null  float64
 9   TARGET(PRICE_IN_LACS)  29451 non-null  float64
 10  Builder                29451 non-null  uint8  
 11  Dealer                 29451 non-null  uint8  
 12  Owner                  29451 non-null  uint8  
dtypes: float64(4), int64(6), uint8(3)
memory usage: 2.3 MB


In [13]:
data['Builder'] = data['Builder'].astype(int)
data['Dealer'] = data['Dealer'].astype(int)
data['Owner'] = data['Owner'].astype(int)

In [14]:
data.head()

UNDER_CONSTRUCTION  RERA  BHK_NO.  BHK_OR_RK    SQUARE_FT  READY_TO_MOVE  \
0                   0     0        2          1  1300.236407              1   
1                   0     0        2          1  1275.000000              1   
2                   0     0        2          1   933.159722              1   
3                   0     1        2          1   929.921143              1   
4                   1     0        2          1   999.009247              0   

   RESALE  LONGITUDE   LATITUDE  TARGET(PRICE_IN_LACS)  Builder  Dealer  Owner  
0       1  12.969910  77.597960                   55.0        0       0      1  
1       1  12.274538  76.644605                   51.0        0       1      0  
2       1  12.778033  77.632191                   43.0        0       0      1  
3       1  28.642300  77.344500                   62.5        0       0      1  
4       1  22.592200  88.484911                   60.5        0       1      0

In [15]:
from sklearn.model_selection import train_test_split
x = data.drop(columns = ['TARGET(PRICE_IN_LACS)'])
y = data['TARGET(PRICE_IN_LACS)']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 0)

In [16]:
x_train.shape


(26505, 12)

In [17]:
y_train.shape

(26505,)

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
Input = [('standard', StandardScaler()), ('linear', LinearRegression())]
pipe = Pipeline(Input)
pipe.fit(x_train, y_train)
predict = pipe.predict(x_train)

In [19]:
predict

array([ 97.68868882, 892.25118882, 148.93868882, ..., 194.12618882,
        20.37618882, 123.25118882])

In [20]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_train, predict)
mse

336560.185969892

In [21]:
from sklearn.metrics import r2_score
score = r2_score(y_train, predict)
score

0.24409726677582977

In [22]:
from sklearn.preprocessing import PolynomialFeatures
Input_ = [('scaler', StandardScaler()), ('features', PolynomialFeatures(degree = 4)), ('linear', LinearRegression())]
pipe_ = Pipeline(Input_)
pipe_.fit(x_train, y_train)
predict_ = pipe_.predict(x_train) 

In [23]:
predict_

array([ 74.56071738, 206.33708862, 105.63576631, ..., 143.72182144,
        43.75218825,  84.30182921])

In [24]:
print('MSE', mean_squared_error(y_train, predict_), 'Rsquare', r2_score(y_train, predict_))

MSE 20275.081695484077 Rsquare 0.9544628559501367


In [25]:
test.head()

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0     Owner                   0     0        1       BHK   545.171340   
1    Dealer                   1     1        2       BHK   800.000000   
2    Dealer                   0     0        2       BHK  1257.096513   
3    Dealer                   0     0        3       BHK  1400.329489   
4     Owner                   0     0        1       BHK   430.477830   

   READY_TO_MOVE  RESALE             ADDRESS  LONGITUDE   LATITUDE  
0              1       1        Kamrej,Surat  21.262000  73.047700  
1              0       0     Panvel,Lalitpur  18.966114  73.148278  
2              1       1    New Town,Kolkata  22.592200  88.484911  
3              1       1  Kalwar Road,Jaipur  26.988300  75.584600  
4              1       1   Mai Mandir,Nadiad  22.700000  72.870000

In [26]:
test.isnull().sum()

POSTED_BY             0
UNDER_CONSTRUCTION    0
RERA                  0
BHK_NO.               0
BHK_OR_RK             0
SQUARE_FT             0
READY_TO_MOVE         0
RESALE                0
ADDRESS               0
LONGITUDE             0
LATITUDE              0
dtype: int64

In [27]:
posted_by_ = pd.get_dummies(test['POSTED_BY'])
test = pd.concat([test, posted_by_], axis = 1)
test.drop(columns = ['POSTED_BY'], inplace = True)

In [28]:
for j in test['BHK_OR_RK']:
    if j == 'BHK':
        test['BHK_OR_RK'].replace('BHK', 1, inplace = True)
    elif j == 'RK':
        test['BHK_OR_RK'].replace('RK', 0, inplace = True)

In [29]:
test.drop(columns = ['ADDRESS'], inplace = True)

In [30]:
test

UNDER_CONSTRUCTION  RERA  BHK_NO.  BHK_OR_RK     SQUARE_FT  \
0                       0     0        1          1    545.171340   
1                       1     1        2          1    800.000000   
2                       0     0        2          1   1257.096513   
3                       0     0        3          1   1400.329489   
4                       0     0        1          1    430.477830   
...                   ...   ...      ...        ...           ...   
68715                   0     1        2          1    856.555505   
68716                   0     1        3          1   2304.147465   
68717                   1     1        1          1  33362.792750   
68718                   0     0        2          1   1173.708920   
68719                   0     0        3          1   2439.532944   

       READY_TO_MOVE  RESALE  LONGITUDE   LATITUDE  Builder  Dealer  Owner  
0                  1       1  21.262000  73.047700        0       0      1  
1                  0       0  18.966114  73.148278        0       1      0  
2                  1       1  22.592200  88.484911        0       1      0  
3                  1       1  26.988300  75.584600        0       1      0  
4                  1       1  22.700000  72.870000        0       0      1  
...              ...     ...        ...        ...      ...     ...    ...  
68715              1       1  19.180000  72.963330        0       1      0  
68716              1       1  30.661104  76.746082        0       1      0  
68717              0       0  19.222101  72.988231        0       1      0  
68718              1       1  18.496670  73.941670        0       1      0  
68719              1       1  19.124896  72.893503        0       1      0  

[68720 rows x 12 columns]

In [31]:
submission = pipe_.predict(test)
submission.reshape(68720, 1)

array([[  22.13115269],
       [ 153.88955749],
       [  43.63943001],
       ...,
       [7698.91504444],
       [ 131.12013251],
       [ 439.66213956]])

In [32]:
submission_price = pd.DataFrame(submission)
submission_price.rename(columns = {0 : 'TARGET(PRICE_IN_LACS)'}, inplace = True)

In [33]:
submission_price

TARGET(PRICE_IN_LACS)
0                  22.131153
1                 153.889557
2                  43.639430
3                 121.390695
4                  15.616481
...                      ...
68715             118.223662
68716              95.880187
68717            7698.915044
68718             131.120133
68719             439.662140

[68720 rows x 1 columns]